// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Povio.FlowerSpot.Persistence;

#nullable disable

namespace Povio.FlowerSpot.Persistence.Migrations
{
    [DbContext(typeof(FlowerSpotDbContext))]
    [Migration("20221124145025_AddQuoteToSighting")]
    partial class AddQuoteToSighting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Flower", b =>
                {
                    b.Property<int>("FlowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlowerId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlowerId");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Like", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("SightingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SightingId");

                    b.HasIndex("SightingId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Sighting", b =>
                {
                    b.Property<int>("SightingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SightingId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlowerId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SightingId");

                    b.HasIndex("FlowerId");

                    b.HasIndex("UserId");

                    b.ToTable("Sighting");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2022, 11, 24, 14, 50, 25, 602, DateTimeKind.Utc).AddTicks(7091),
                            Email = "test@test.com",
                            Password = "test",
                            Username = "test"
                        });
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Like", b =>
                {
                    b.HasOne("Povio.FlowerSpot.Domain.Entities.Sighting", "Sighting")
                        .WithMany("Likes")
                        .HasForeignKey("SightingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Povio.FlowerSpot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sighting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Sighting", b =>
                {
                    b.HasOne("Povio.FlowerSpot.Domain.Entities.Flower", "Flower")
                        .WithMany()
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Povio.FlowerSpot.Domain.Entities.User", "User")
                        .WithMany("Sightings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Povio.FlowerSpot.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("SightingId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric")
                                .HasColumnName("Longitude");

                            b1.HasKey("SightingId");

                            b1.ToTable("Sighting");

                            b1.WithOwner()
                                .HasForeignKey("SightingId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Flower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.Sighting", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Povio.FlowerSpot.Domain.Entities.User", b =>
                {
                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
