version: '3.8'
services:
  db:
    container_name: 'postgres'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./src/Povio.FlowerSpot/Data:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - povio-network
networks:
  povio-network:
    name: povio-flower-spot-network